# Generated by Django 4.2.7 on 2024-02-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_password_text_passwordstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
