# Generated by Django 4.2.7 on 2024-03-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDetails',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('employee_id', models.BigIntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('p', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_leave', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overtime_hours', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'attendance_details',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('employee_id', models.BigIntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('status_change_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'attendance_log',
            },
        ),
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'company_master',
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('daily_attendance_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('employee_id', models.BigIntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('p', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_leave', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_time', models.CharField(blank=True, max_length=255, null=True)),
                ('out_time', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('overtime_hours', models.TimeField(blank=True, null=True)),
                ('is_overtime', models.IntegerField(blank=True, default='0', null=True)),
                ('sss', models.IntegerField(blank=True, default='0', null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'daily_attendance',
            },
        ),
        migrations.CreateModel(
            name='EarlyLeaveApply',
            fields=[
                ('early_leave_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('employee_id', models.BigIntegerField(blank=True, null=True)),
                ('leave_date', models.DateField(blank=True, default=None, null=True)),
                ('leave_time', models.TimeField(blank=True, default=None, null=True)),
                ('reason_for_leave', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'early_leave_application',
            },
        ),
        migrations.CreateModel(
            name='LeaveApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.BigIntegerField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, default=None, null=True)),
                ('to_date', models.DateField(blank=True, default=None, null=True)),
                ('leave_id', models.IntegerField(blank=True, null=True)),
                ('reason_for_leave', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('leave_status_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'leave_application_details',
            },
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'location_master',
            },
        ),
        migrations.CreateModel(
            name='ShiftMaster',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('shift_name', models.CharField(blank=True, max_length=255, null=True)),
                ('in_shift_time', models.TimeField(blank=True, max_length=255, null=True)),
                ('out_shift_time', models.TimeField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'shift_master',
            },
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'status_master',
            },
        ),
        migrations.CreateModel(
            name='UserRelationMaster',
            fields=[
                ('user_relation_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.BigIntegerField(blank=True, max_length=255, null=True)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
                ('location_id', models.BigIntegerField(blank=True, null=True)),
                ('shift_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_relation_master',
            },
        ),
    ]
