# Generated by Django 4.2.7 on 2024-03-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='ddd',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
