# Generated by Django 4.2.7 on 2024-03-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_dailyattendance_ddd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyattendance',
            name='ddd',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='is_overtime',
        ),
        migrations.RemoveField(
            model_name='dailyattendance',
            name='sss',
        ),
    ]
