# Generated by Django 4.2.7 on 2024-03-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_dailyattendance_ddd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='is_overtime',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
