# Generated by Django 4.2.7 on 2024-03-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_dailyattendance_is_overtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCorrection',
            fields=[
                ('correction_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.BigIntegerField(blank=True, max_length=255, null=True)),
                ('title', models.BigIntegerField(blank=True, null=True)),
                ('correction_date', models.BigIntegerField(blank=True, null=True)),
                ('corrected_time', models.BigIntegerField(blank=True, null=True)),
                ('reason_for_correction', models.BigIntegerField(blank=True, null=True)),
                ('correction_type', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'time_correction',
            },
        ),
    ]
