# Generated by Django 4.2.7 on 2024-03-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_timecorrection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecorrection',
            name='corrected_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='correction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='correction_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='reason_for_correction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
