# Generated by Django 4.2.7 on 2024-03-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_timecorrection_corrected_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecorrection',
            name='status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
