# Generated by Django 4.2.7 on 2024-03-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_timecorrection_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='overtime_hours',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
