# Generated by Django 4.2.7 on 2024-03-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapply',
            name='leave_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
